name: Release

on:
  push:
    branches:
      - main
      - main-test-changesets

permissions:
  id-token: write  # Required for OIDC
  contents: write # Required for changesets to commit changes
  pull-requests: write # Required for changesets to create PRs

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Installation
        run: npm ci

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ""
